#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mch_book add column

Revision ID: 035fa6373ba0
Revises: c763e561ad8d
Create Date: 2017-10-12 14:47:55.058228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '035fa6373ba0'
down_revision = 'c763e561ad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_book', sa.Column('bank_d0_cost', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('bp_d0_profit', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('bp_trade_profit',
                                        sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('d0_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('dt_d0_profit', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('dt_trade_profit',
                                        sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('mch_d0_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('mch_trade_fee', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('pay_channel_profit',
                                        sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('refund_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('trade_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_book', 'trade_count')
    op.drop_column('mch_book', 'status')
    op.drop_column('mch_book', 'refund_count')
    op.drop_column('mch_book', 'pay_channel_profit')
    op.drop_column('mch_book', 'mch_trade_fee')
    op.drop_column('mch_book', 'mch_d0_fee')
    op.drop_column('mch_book', 'dt_trade_profit')
    op.drop_column('mch_book', 'dt_d0_profit')
    op.drop_column('mch_book', 'd0_count')
    op.drop_column('mch_book', 'bp_trade_profit')
    op.drop_column('mch_book', 'bp_d0_profit')
    op.drop_column('mch_book', 'bank_d0_cost')
    # ### end Alembic commands ###
