#!/usr/bin/env python
#-*- coding: utf-8 -*-
"""add d0

Revision ID: 04bef4af514a
Revises: 914dd041b12e
Create Date: 2017-04-25 17:59:21.912188

"""
# 实现D0需求新增的表, 商户资产表，d0提现记录表，商户清分表添加2个字段变成资金流水表
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04bef4af514a'
down_revision = '914dd041b12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d0_withdraw',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('d0_trand_id', sa.BigInteger(), nullable=True),
                    sa.Column('mch_d0_trand_id', sa.String(length=64), nullable=True),
                    sa.Column('mch_id', sa.BigInteger(), nullable=False),
                    sa.Column('busitype', sa.SmallInteger(), nullable=True),
                    sa.Column('rcvacctno', sa.String(length=64), nullable=True),
                    sa.Column('rcvbankname', sa.String(length=128), nullable=True),
                    sa.Column('rcvbanksettleno', sa.String(length=12), nullable=True),
                    sa.Column('rcvacctname', sa.String(length=64), nullable=True),
                    sa.Column('raw_tranamt', sa.BigInteger(), nullable=True),
                    sa.Column('fee', sa.BigInteger(), nullable=True),
                    sa.Column('dt_id', sa.BigInteger(), nullable=True),
                    sa.Column('dt_fee', sa.BigInteger(), nullable=True),
                    sa.Column('p_fee', sa.BigInteger(), nullable=True),
                    sa.Column('tranamt', sa.BigInteger(), nullable=False),
                    sa.Column('pay_start_time', sa.DateTime(), nullable=True),
                    sa.Column('pay_end_time', sa.DateTime(), nullable=True),
                    sa.Column('pay_status', sa.SmallInteger(), nullable=False),
                    sa.Column('failure_details', sa.String(length=128), nullable=True),
                    sa.Column('check_status', sa.SmallInteger(), nullable=True),
                    sa.Column('channel', sa.String(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('mch_asset',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), nullable=True),
                    sa.Column('wx_total', sa.BigInteger(), nullable=True),
                    sa.Column('wx_freeze', sa.BigInteger(), nullable=True),
                    sa.Column('ali_total', sa.BigInteger(), nullable=True),
                    sa.Column('ali_freeze', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('mch_id')
                    )

    op.add_column(u'dt_clear_info', sa.Column('business_type', sa.SmallInteger(), nullable=True))
    op.add_column(u'dt_clear_info', sa.Column('current_balance', sa.SmallInteger(), nullable=True))
    op.add_column(u'dt_clear_info', sa.Column('remarks', sa.String(length=256), nullable=True))

    op.add_column(u'dt_daily_balance_info', sa.Column('d0_withdraw_profit', sa.BigInteger(), nullable=True))

    op.add_column(u'mch_clear_info', sa.Column('business_type', sa.SmallInteger(), nullable=True))
    op.add_column(u'mch_clear_info', sa.Column('current_balance', sa.BigInteger(), nullable=True))
    op.add_column(u'mch_clear_info', sa.Column('remarks', sa.String(length=256), nullable=True))
    op.add_column(u'mch_daily_balance_info', sa.Column('d0_withdraw', sa.BigInteger(), nullable=True))
    op.add_column(u'mch_daily_balance_info', sa.Column('d0_withdraw_fee', sa.BigInteger(), nullable=True))
    op.add_column(u'p_daily_balance_info', sa.Column('d0_withdraw_profit', sa.BigInteger(), nullable=True))

    op.add_column('dt_clear_info', sa.Column('channel', sa.String(length=32), nullable=True))
    op.add_column('mch_clear_info', sa.Column('channel', sa.String(length=32), nullable=True))

    op.add_column('dt_clear_info', sa.Column('trade_date', sa.Date(), nullable=True))
    op.add_column('mch_clear_info', sa.Column('trade_date', sa.Date(), nullable=True))
    op.add_column('p_clear_info', sa.Column('trade_date', sa.Date(), nullable=True))

    op.execute('COMMIT')
    op.create_index(op.f('ix_d0_withdraw_d0_trand_id'), 'd0_withdraw', [
                    'd0_trand_id'], unique=False, postgresql_concurrently=True)
    op.create_index(op.f('ix_d0_withdraw_mch_d0_trand_id'), 'd0_withdraw', [
                    'mch_d0_trand_id'], unique=False, postgresql_concurrently=True)
    op.create_index(op.f('ix_mch_clear_info_trade_date'), 'mch_clear_info', [
                    'trade_date'], unique=False, postgresql_concurrently=True)
    op.create_index(op.f('ix_dt_clear_info_trade_date'), 'dt_clear_info', [
                    'trade_date'], unique=False, postgresql_concurrently=True)
    op.create_index(op.f('ix_p_clear_info_trade_date'), 'p_clear_info', [
                    'trade_date'], unique=False, postgresql_concurrently=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'p_daily_balance_info', 'd0_withdraw_profit')
    op.drop_column(u'mch_daily_balance_info', 'd0_withdraw_fee')
    op.drop_column(u'mch_daily_balance_info', 'd0_withdraw')
    op.drop_column(u'mch_clear_info', 'remarks')
    op.drop_column(u'mch_clear_info', 'current_balance')
    op.drop_column(u'mch_clear_info', 'business_type')

    op.drop_column(u'dt_daily_balance_info', 'd0_withdraw_profit')
    op.drop_column(u'dt_clear_info', 'remarks')
    op.drop_column(u'dt_clear_info', 'current_balance')
    op.drop_column(u'dt_clear_info', 'business_type')

    op.drop_table('mch_asset')
    op.drop_index(op.f('ix_d0_withdraw_mch_d0_trand_id'), table_name='d0_withdraw')
    op.drop_index(op.f('ix_d0_withdraw_d0_trand_id'), table_name='d0_withdraw')
    op.drop_table('d0_withdraw')

    op.drop_column('mch_clear_info', 'channel')
    op.drop_column('dt_clear_info', 'channel')

    op.drop_index(op.f('ix_p_clear_info_trade_date'), table_name='p_clear_info')
    op.drop_column('p_clear_info', 'trade_date')
    op.drop_index(op.f('ix_mch_clear_info_trade_date'), table_name='mch_clear_info')
    op.drop_column('mch_clear_info', 'trade_date')
    op.drop_index(op.f('ix_dt_clear_info_trade_date'), table_name='dt_clear_info')
    op.drop_column('dt_clear_info', 'trade_date')
    # ### end Alembic commands ###
