#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""unionpay add column

Revision ID: 246a728e54d3
Revises: e8903a5ed0e4
Create Date: 2017-10-30 17:43:25.311404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '246a728e54d3'
down_revision = '510db6a84eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('head_mobile', sa.String(length=15), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('head_name', sa.String(length=20), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('img_with_id_card', sa.String(length=200), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('unionpay_id', sa.String(length=32), nullable=True))
    op.add_column('dt_user', sa.Column('unionpay_level', sa.String(length=32), nullable=True))
    op.add_column('dt_user', sa.Column('unionpay_limit', sa.String(length=32), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('head_mobile', sa.String(length=15), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('head_name', sa.String(length=20), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('img_with_id_card', sa.String(length=200), nullable=True))
    op.add_column('mch_user', sa.Column('unionpay_level', sa.String(length=32), nullable=True))
    op.add_column('mch_user', sa.Column('unionpay_limit', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_user', 'unionpay_limit')
    op.drop_column('mch_user', 'unionpay_level')
    op.drop_column('mch_inlet_info', 'img_with_id_card')
    op.drop_column('mch_inlet_info', 'head_name')
    op.drop_column('mch_inlet_info', 'head_mobile')
    op.drop_column('dt_user', 'unionpay_limit')
    op.drop_column('dt_user', 'unionpay_level')
    op.drop_column('dt_inlet_info', 'unionpay_id')
    op.drop_column('dt_inlet_info', 'img_with_id_card')
    op.drop_column('dt_inlet_info', 'head_name')
    op.drop_column('dt_inlet_info', 'head_mobile')
    # ### end Alembic commands ###
