#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""new_inlet_auth

Revision ID: 27d9edda20c3
Revises: 6f2d14437141
Create Date: 2017-11-27 15:20:26.281970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27d9edda20c3'
down_revision = '6f2d14437141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'inlet_auth_items',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('sys_id', sa.BigInteger(), nullable=False),
        sa.Column('sys_type_id', sa.String(length=64), nullable=False),
        sa.Column('sys_name', sa.String(length=64), nullable=False),
        sa.Column('sys_shortname', sa.String(length=64), nullable=False),
        sa.Column('dt_id', sa.BigInteger(), nullable=True),
        sa.Column('dt_name', sa.String(length=64), nullable=True),
        sa.Column('backup_content', sa.TEXT(), nullable=True),
        sa.Column('change_record_id', sa.BigInteger(), nullable=False),
        sa.Column('inlet_type', sa.SmallInteger(), nullable=False),
        sa.Column('submitter_id', sa.BigInteger(), nullable=False),
        sa.Column('submitter_name', sa.String(length=64), nullable=True),
        sa.Column('submitter_type', sa.String(length=10), nullable=True),
        sa.Column('auth_status', sa.Integer(), nullable=False),
        sa.Column('auth_comment', sa.String(length=200), nullable=True),
        sa.Column('create_time', sa.DateTime(), nullable=False),
        sa.Column('update_time', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inlet_auth_items')
    # ### end Alembic commands ###
