"""all user add api_key field

Revision ID: 2b04470963e4
Revises:
Create Date: 2016-11-28 21:19:08.252691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from uline.model.uline.user import DtUser

Session = sessionmaker()


# revision identifiers, used by Alembic.
revision = '2b04470963e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bk_user', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('dt_user', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('mch_user', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('ub_user', sa.Column('api_key', sa.String(length=64), nullable=True))
    ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)

    user = session.query(DtUser).filter_by(dt_id='10000000830').first()

    if user:
        user.api_key = '7290C9989626D3D78496CA831FDAB3CC'
    session.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ub_user', 'api_key')
    op.drop_column('mch_user', 'api_key')
    op.drop_column('dt_user', 'api_key')
    op.drop_column('bk_user', 'api_key')
    ### end Alembic commands ###
