"""add trand_id field

Revision ID: 2c5e04c7efd3
Revises: 20e682fe2cc8
Create Date: 2017-01-10 11:18:21.982158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from uline.public.db import initdb
from uline.model.uline.balance import MchDailyBalanceInfo, DtDailyBalanceInfo, PDailyBalanceInfo

initdb()
Session = sessionmaker()


# revision identifiers, used by Alembic.
revision = '2c5e04c7efd3'
down_revision = '20e682fe2cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_daily_balance_info', sa.Column('dt_trand_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_dt_daily_balance_info_dt_trand_id'),
                    'dt_daily_balance_info', ['dt_trand_id'], unique=False)
    op.add_column('mch_daily_balance_info', sa.Column('mch_trand_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_mch_daily_balance_info_mch_trand_id'),
                    'mch_daily_balance_info', ['mch_trand_id'], unique=False)
    op.add_column('p_daily_balance_info', sa.Column('p_trand_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_p_daily_balance_info_p_trand_id'),
                    'p_daily_balance_info', ['p_trand_id'], unique=False)

    bind = op.get_bind()
    session = Session(bind=bind)

    for i in session.query(MchDailyBalanceInfo):
        i.mch_trand_id = i.mch_daily_balance_no
    for i in session.query(DtDailyBalanceInfo):
        i.dt_trand_id = i.dt_daily_balance_no
    for i in session.query(PDailyBalanceInfo):
        i.p_trand_id = i.p_daily_balance_no
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_p_daily_balance_info_p_trand_id'), table_name='p_daily_balance_info')
    op.drop_column('p_daily_balance_info', 'p_trand_id')
    op.drop_index(op.f('ix_mch_daily_balance_info_mch_trand_id'), table_name='mch_daily_balance_info')
    op.drop_column('mch_daily_balance_info', 'mch_trand_id')
    op.drop_index(op.f('ix_dt_daily_balance_info_dt_trand_id'), table_name='dt_daily_balance_info')
    op.drop_column('dt_daily_balance_info', 'dt_trand_id')
    # ### end Alembic commands ###
