#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""wechat app channel id

Revision ID: 38720cafbda5
Revises: 154abf307825
Create Date: 2017-05-11 15:49:39.953385

"""

"""
增加渠道商微信app支付微信渠道号字段
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38720cafbda5'
down_revision = '154abf307825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dt_inlet_info', sa.Column('wx_app_channel_id', sa.String(length=32), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dt_inlet_info', 'wx_app_channel_id')
