#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""auth item add bk id

Revision ID: 3b079a89d328
Revises: a2fae5769b8b
Create Date: 2017-12-06 17:50:10.138229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b079a89d328'
down_revision = 'a2fae5769b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inlet_auth_items', sa.Column('bk_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inlet_auth_items', 'bk_id')
    # ### end Alembic commands ###
