"""add mch_user_mch_subuser

Revision ID: 4972ce55e188
Revises: b07b96c7dc73
Create Date: 2017-07-03 16:44:31.578984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

# revision identifiers, used by Alembic.
revision = '4972ce55e188'
down_revision = '692354f8f177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('mch_user_mch_subuser',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), nullable=True),
                    sa.Column('mch_sub_id', sa.BigInteger(), nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('mch_id', 'mch_sub_id')
                    )
    op.execute(CreateSequence(Sequence('tb_mch_user_subuser_id_seq', start=1)))

    op.execute(
        'insert into mch_user_mch_subuser (mch_id, mch_sub_id) select mch_id ,mch_sub_id from mch_subuser where mch_id is not null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mch_user_mch_subuser')
    # ### end Alembic commands ###
