"""mch inlet notify url

Revision ID: 4c070deaec2e
Revises: 2b04470963e4
Create Date: 2016-12-02 11:03:41.150969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c070deaec2e'
down_revision = '2b04470963e4'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_inlet_info', sa.Column('notify_count', sa.SmallInteger(), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('notify_successed', sa.SmallInteger(), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('notify_url', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_inlet_info', 'notify_url')
    op.drop_column('mch_inlet_info', 'notify_successed')
    op.drop_column('mch_inlet_info', 'notify_count')
    ### end Alembic commands ###
