"""add table industry_new_ali_info

Revision ID: 4c3d23c10f6a
Revises: faadc55299de
Create Date: 2017-06-15 15:36:19.081703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c3d23c10f6a'
down_revision = 'faadc55299de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'industry_uline_info', sa.Column('new_ali_ind_code', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_new_ali_info')
    # ### end Alembic commands ###
