#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""platform_mch table add op_user_id op_user_passwd

Revision ID: 4d0a2cdeef16
Revises: d5c386cd68cf
Create Date: 2017-12-13 17:33:24.169938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d0a2cdeef16'
down_revision = 'd5c386cd68cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_mch', sa.Column('op_user_id', sa.String(
        length=64), server_default='', nullable=False))
    op.add_column('platform_mch', sa.Column('op_user_passwd',
                                            sa.String(length=256), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_mch', 'op_user_passwd')
    op.drop_column('platform_mch', 'op_user_id')
    # ### end Alembic commands ###
