"""modifycommentlength

Revision ID: 4e41438631c4
Revises: de2db21d571b
Create Date: 2017-05-26 16:26:54.992495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e41438631c4'
down_revision = 'de2db21d571b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'auth_dt_info', 'comment',
                    existing_type=sa.String(64),
                    type_=sa.String(1024),
                    existing_nullable=False)
    op.alter_column(u'auth_mch_info', 'comment',
                    existing_type=sa.String(64),
                    type_=sa.String(1024),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
