"""add table pre_trade_clear_info pre_refund_clear_info pre_d0_clear_info

Revision ID: 501ae56f8814
Revises: 83c8b28a5cd0
Create Date: 2017-08-21 14:28:41.613682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '501ae56f8814'
down_revision = '83c8b28a5cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_d0_clear_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('out_trade_no', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('busitype', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('mch_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_settle_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('settlement', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('draw_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('draw_profit', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('draw_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('total_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('mch_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('dt_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('dt_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('dt_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('bp_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pre_refund_clear_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('out_trade_no', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('transaction_id', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('out_refund_no', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_settle_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('trade_type', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('platform_mch_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('total_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('refund_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('mch_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('dt_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('dt_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('pay_channel_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pay_channel_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('bp_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pre_trade_clear_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('out_trade_no', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('transaction_id', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_payment_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('uline_settle_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('trade_type', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('platform_mch_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('total_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('mch_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('mch_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('dt_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('dt_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('pay_channel_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('pay_channel_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('bp_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('complete_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_trade_clear_info')
    op.drop_table('pre_refund_clear_info')
    op.drop_table('pre_d0_clear_info')
    # ### end Alembic commands ###
