#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""inlet table add jd_ind_code

Revision ID: 510db6a84eef
Revises: f3e917ae04ed
Create Date: 2017-11-02 18:29:22.966967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '510db6a84eef'
down_revision = 'f3e917ae04ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('jd_ind_code', sa.String(length=40), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('jd_ind_code', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_refund_clear_info', 'complete_at')
    op.drop_column('mch_inlet_info', 'jd_ind_code')
    op.drop_column('dt_inlet_info', 'jd_ind_code')
    # ### end Alembic commands ###
