"""trade risk info column

Revision ID: 5409015763ec
Revises: a937823f334c
Create Date: 2017-09-26 18:54:05.059765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5409015763ec'
down_revision = 'a937823f334c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_risk', sa.Column('platform', sa.String(length=64), nullable=True))
    op.drop_column('trade_risk', 'platfrom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_risk', sa.Column('platfrom', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('trade_risk', 'platform')
    # ### end Alembic commands ###
