"""remove bank_no index(exists multi record)

Revision ID: 54fed045c733
Revises: df25824f0ffc
Create Date: 2016-12-08 15:53:23.718254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fed045c733'
down_revision = 'df25824f0ffc'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_bank_info_bank_no', table_name='balance_bank_info')
    op.create_index(op.f('ix_balance_bank_info_bank_no'), 'balance_bank_info', ['bank_no'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_bank_info_bank_no'), table_name='balance_bank_info')
    op.create_index('ix_balance_bank_info_bank_no', 'balance_bank_info', ['bank_no'], unique=True)
    ### end Alembic commands ###
