"""dt_inlet_info table add district column

Revision ID: 5dbf6e49ee9e
Revises: ee8edd2d8d81
Create Date: 2017-06-21 10:27:44.009656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dbf6e49ee9e'
down_revision = 'ee8edd2d8d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('district', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_inlet_info', 'district')
    # ### end Alembic commands ###
