#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""auth item balance type

Revision ID: 602a2a281c9b
Revises: 3b079a89d328
Create Date: 2017-12-07 11:18:56.966839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602a2a281c9b'
down_revision = '3b079a89d328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inlet_auth_items', sa.Column('balance_type', sa.SmallInteger(), nullable=True))
    op.add_column('inlet_auth_items', sa.Column('newest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inlet_auth_items', 'newest')
    op.drop_column('inlet_auth_items', 'balance_type')
    # ### end Alembic commands ###
