"""Add dtpayment news_push_open_status column

Revision ID: 67d02e8fdccf
Revises: a32840e24f95
Create Date: 2017-06-23 14:30:11.645171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67d02e8fdccf'
down_revision = 'a32840e24f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_payment', sa.Column('news_push_open_status',
                                          sa.Integer(), server_default=sa.text(u'3'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_payment', 'news_push_open_status')
    # ### end Alembic commands ###
