"""create table uline_payment, uline_settle, platform_mch, update mch_payment dt_payment

Revision ID: 6863e951b279
Revises: bbeb0ff78b56
Create Date: 2017-08-18 18:43:08.157154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6863e951b279'
down_revision = 'e8903a5ed0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bank_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('profit_total', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('cut_date', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('platform_mch',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('channel_code', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('app_id', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('mch_id', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('pay_key', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('pub_key', sa.Text(), server_default='', nullable=False),
                    sa.Column('private_key', sa.Text(), server_default='', nullable=False),
                    sa.Column('settle_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('uline_payment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('payment_code', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('pay_channel', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('trade_type', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('payment_type', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('settle_rate', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('check_status', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('channel_code', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('platform_mch_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=512), server_default='', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('uline_settle',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), server_default='', nullable=False),
                    sa.Column('settlement', sa.SmallInteger(), server_default='1', nullable=False),
                    sa.Column('draw_type', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('default_d1', sa.Boolean(), server_default='True', nullable=False),
                    sa.Column('draw_rate', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('draw_profit', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('draw_low', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('draw_high', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('bank_id', sa.Integer(), server_default='0', nullable=False),
                    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=512), server_default='', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'dt_payment', sa.Column('settle_rate', sa.Integer(), nullable=True))
    op.add_column(u'dt_payment', sa.Column('thirdparty_mch_id', sa.String(length=64), nullable=True))
    op.add_column(u'dt_payment', sa.Column('trade_type', sa.String(length=64), nullable=True))
    op.add_column(u'dt_payment', sa.Column('uline_payment_id', sa.Integer(), nullable=True))
    op.add_column(u'dt_payment', sa.Column('uline_settle_id', sa.Integer(), nullable=True))
    op.add_column(u'mch_payment', sa.Column('dt_id', sa.BigInteger(), nullable=True))
    op.add_column(u'mch_payment', sa.Column('settle_rate', sa.Integer(), nullable=True))
    op.add_column(u'mch_payment', sa.Column('thirdparty_mch_id', sa.String(length=64), nullable=True))
    op.add_column(u'mch_payment', sa.Column('trade_type', sa.String(length=64), nullable=True))
    op.add_column(u'mch_payment', sa.Column('uline_payment_id', sa.Integer(), nullable=True))
    op.add_column(u'mch_payment', sa.Column('uline_settle_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'mch_payment', 'uline_settle_id')
    op.drop_column(u'mch_payment', 'uline_payment_id')
    op.drop_column(u'mch_payment', 'trade_type')
    op.drop_column(u'mch_payment', 'thirdparty_mch_id')
    op.drop_column(u'mch_payment', 'settle_rate')
    op.drop_column(u'mch_payment', 'dt_id')
    op.drop_column(u'dt_payment', 'uline_settle_id')
    op.drop_column(u'dt_payment', 'uline_payment_id')
    op.drop_column(u'dt_payment', 'trade_type')
    op.drop_column(u'dt_payment', 'thirdparty_mch_id')
    op.drop_column(u'dt_payment', 'settle_rate')
    op.drop_table('uline_settle')
    op.drop_table('uline_payment')
    op.drop_table('platform_mch')
    op.drop_table('bank_info')
    # ### end Alembic commands ###
