#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""wx_return_info_length

Revision ID: 692354f8f177
Revises: 4972ce55e188
Create Date: 2017-07-05 09:50:43.849562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692354f8f177'
down_revision = 'b07b96c7dc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dt_inlet_to_wx_info', 'result_msg',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=True)
    op.alter_column('dt_inlet_to_wx_info', 'return_msg',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=True)
    op.alter_column('mch_inlet_to_wx_info', 'result_msg',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=False)
    op.alter_column('mch_inlet_to_wx_info', 'return_msg',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mch_inlet_to_wx_info', 'return_msg',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=False)
    op.alter_column('mch_inlet_to_wx_info', 'result_msg',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=False)
    op.alter_column('dt_inlet_to_wx_info', 'return_msg',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    op.alter_column('dt_inlet_to_wx_info', 'result_msg',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    # ### end Alembic commands ###
