"""daily cut record

Revision ID: 6bba77a8cad7
Revises: 2fafb5abedb5
Create Date: 2017-08-29 11:06:38.199498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bba77a8cad7'
down_revision = '2fafb5abedb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cut_record',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=True),
                    sa.Column('role_type', sa.String(length=64), nullable=False),
                    sa.Column('record_json', sa.TEXT(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_cut_record')
    # ### end Alembic commands ###
