"""trade risk info column type

Revision ID: 6bd32a87b858
Revises: 5409015763ec
Create Date: 2017-09-26 19:39:49.812382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bd32a87b858'
down_revision = '5409015763ec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_risk', 'content',
                    existing_type=sa.String(length=500),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_risk', 'content',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=500),
                    existing_nullable=True)
    # ### end Alembic commands ###
