"""create table d0_repayment

Revision ID: 6d6a80db5948
Revises: d62ac1b61a84
Create Date: 2017-08-29 14:25:52.464219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d6a80db5948'
down_revision = 'd62ac1b61a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d0_repayment',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('loan_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('repayment_id', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('repayment_amount', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('draw_fee', sa.BigInteger(), server_default='0', nullable=False),
                    sa.Column('repayment_status', sa.SmallInteger(), server_default='0', nullable=False),
                    sa.Column('remark', sa.String(length=128), server_default='', nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('d0_repayment')
    # ### end Alembic commands ###
