"""changerecord add data_json field

Revision ID: 6ec19e689a73
Revises: 334a1651d98d
Create Date: 2017-03-17 17:08:03.567544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec19e689a73'
down_revision = '334a1651d98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_record', sa.Column('data_json', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_record', 'data_json')
    # ### end Alembic commands ###
