#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""gather mchs activated email

Revision ID: 6f2d14437141
Revises: a96d0d88e1fd
Create Date: 2017-11-15 18:10:12.669994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f2d14437141'
down_revision = 'a96d0d88e1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gather_mchs_email_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), nullable=False),
                    sa.Column('email', sa.String(length=64), nullable=False),
                    sa.Column('download_url', sa.String(length=128), nullable=False),
                    sa.Column('status', sa.Integer(), server_default=sa.text(u'0'), nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('gather_mchs_email_info_dt_id_index', 'gather_mchs_email_info', ['dt_id'], unique=False)

    op.add_column('dt_inlet_info', sa.Column('activate_email_tag',
                                             sa.Integer(), server_default=sa.text(u'1'), nullable=True))

    op.add_column('mch_inlet_info', sa.Column('activate_email_tag',
                                              sa.Integer(), server_default=sa.text(u'1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('mch_inlet_info', 'activate_email_tag')

    op.drop_column('dt_inlet_info', 'activate_email_tag')

    op.drop_index('gather_mchs_email_info', table_name='gather_mchs_email_info')
    op.drop_table('gather_mchs_email_info')
    # ### end Alembic commands ###
