#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""dt_inlet_info add columns annex_img 1-5

Revision ID: 71093145ada3
Revises: cdf090684bd6
Create Date: 2017-12-01 10:33:38.620514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71093145ada3'
down_revision = 'cdf090684bd6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('annex_img1', sa.String(length=200), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('annex_img2', sa.String(length=200), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('annex_img3', sa.String(length=200), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('annex_img4', sa.String(length=200), nullable=True))
    op.add_column('dt_inlet_info', sa.Column('annex_img5', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_inlet_info', 'annex_img5')
    op.drop_column('dt_inlet_info', 'annex_img4')
    op.drop_column('dt_inlet_info', 'annex_img3')
    op.drop_column('dt_inlet_info', 'annex_img2')
    op.drop_column('dt_inlet_info', 'annex_img1')
    # ### end Alembic commands ###
