#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""add d0 repayment_amount

Revision ID: 72122a41d691
Revises: 31f6bc04631c
Create Date: 2017-05-16 17:22:17.819058

"""
from alembic import op
import sqlalchemy as sa

# 方便处理,为D0增加还款金额

# revision identifiers, used by Alembic.
revision = '72122a41d691'
down_revision = '31f6bc04631c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('d0_withdraw', sa.Column('addition_repayment_amount', sa.BigInteger(), nullable=True))
    op.add_column('d0_withdraw', sa.Column('repayment_amount', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('d0_withdraw', 'repayment_amount')
    op.drop_column('d0_withdraw', 'addition_repayment_amount')

    # ### end Alembic commands ###
