"""platform_mch table add column alias_name

Revision ID: 724cd912228b
Revises: 87850318a305
Create Date: 2017-08-21 16:51:26.045858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '724cd912228b'
down_revision = '87850318a305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_mch', sa.Column('alias_name', sa.String(
        length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_mch', 'alias_name')
    # ### end Alembic commands ###
