# -*- coding: utf-8 -*-
"""modify dt_sub_user

Revision ID: 79cecbbb4f69
Revises: 4eb454bdb4e7
Create Date: 2017-04-14 15:45:48.796416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence
from sqlalchemy.dialects import postgresql


# 修改渠道商子账户表
# revision identifiers, used by Alembic.
revision = '79cecbbb4f69'
down_revision = '4eb454bdb4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除掉旧的数据， 里面存储了毫无意义的数据, 而且会影响后面字段的修改
    op.execute('delete from dt_subuser')
    op.add_column('dt_subuser', sa.Column('login_name', sa.String(length=64), nullable=False))
    op.add_column('dt_subuser', sa.Column('phone', sa.String(length=64), nullable=False))
    op.alter_column('dt_subuser', 'status',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text(u'0'))
    op.execute("DROP INDEX IF EXISTS dt_subuser_index")
    op.create_index('dt_subuser_index', 'dt_subuser', ['dt_sub_id'], unique=True)

    # 修改渠道商信息表
    op.add_column(u'mch_inlet_info', sa.Column('dt_sub_id', sa.BigInteger(), nullable=True))
    op.create_index('mch_info_dt_sub_id_index', 'mch_inlet_info', ['dt_sub_id'], unique=False)
    op.execute(CreateSequence(Sequence('tb_dt_sub_id_seq', start=10000000)))
    op.drop_constraint(u'dt_subuser_dt_user_dt_id_fkey', 'dt_subuser', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key(u'dt_subuser_dt_user_dt_id_fkey', 'dt_subuser', 'dt_user', ['dt_user_dt_id'], ['dt_id'])
    op.drop_index('mch_info_dt_sub_id_index', table_name='mch_inlet_info')
    op.drop_column('mch_inlet_info', 'dt_sub_id')
    op.add_column('dt_subuser', sa.Column('mch_pay_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('dt_subuser', sa.Column('rate', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('dt_subuser', sa.Column('wx_sub_mch_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('dt_subuser_email_uindex', 'dt_subuser', ['email'], unique=False)
    op.drop_index('dt_subuser_index', table_name='dt_subuser')
    op.alter_column('dt_subuser', 'status',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text(u'0'))
    op.drop_column('dt_subuser', 'phone')
    op.drop_column('dt_subuser', 'login_name')
    # ### end Alembic commands ###
