"""add new column refund_password to dt_user

Revision ID: 7a834f79f256
Revises: d61ccca3a324
Create Date: 2017-06-12 16:40:35.666254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a834f79f256'
down_revision = 'd61ccca3a324'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dt_user', sa.Column('refund_password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dt_user', 'refund_password')
    # ### end Alembic commands ###
