# -*- coding:utf-8 -*-

"""add cs daily balance

Revision ID: 7f9441cd6b8e
Revises: 9041f2ffdbbb
Create Date: 2017-04-05 17:08:08.924925

"""
from alembic import op
import sqlalchemy as sa

# 连锁店模式添加一张结算汇总表

# revision identifiers, used by Alembic.
revision = '7f9441cd6b8e'
down_revision = '9041f2ffdbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cs_daily_balance_info',
                    sa.Column('cs_daily_balance_no', sa.BigInteger(), nullable=False),
                    sa.Column('cs_trand_id', sa.BigInteger(), nullable=True),
                    sa.Column('cs_id', sa.BigInteger(), nullable=False),
                    sa.Column('busitype', sa.SmallInteger(), nullable=False),
                    sa.Column('rcvacctno', sa.String(length=64), nullable=False),
                    sa.Column('rcvbankname', sa.String(length=128), nullable=False),
                    sa.Column('rcvbanksettleno', sa.String(length=12), nullable=False),
                    sa.Column('rcvacctname', sa.String(length=64), nullable=False),
                    sa.Column('raw_tranamt', sa.BigInteger(), nullable=False),
                    sa.Column('tranamt', sa.BigInteger(), nullable=False),
                    sa.Column('parent_id', sa.BigInteger(), nullable=True),
                    sa.Column('rate', sa.INTEGER(), nullable=True),
                    sa.Column('need_pay_time', sa.DateTime(), nullable=False),
                    sa.Column('pay_start_time', sa.DateTime(), nullable=True),
                    sa.Column('pay_end_time', sa.DateTime(), nullable=True),
                    sa.Column('pay_status', sa.SmallInteger(), nullable=False),
                    sa.Column('failure_details', sa.String(length=128), nullable=True),
                    sa.Column('check_status', sa.SmallInteger(), nullable=False),
                    sa.Column('day_tx_amount', sa.BigInteger(), nullable=False),
                    sa.Column('day_refund_amount', sa.BigInteger(), nullable=False),
                    sa.Column('day_tx_net_amout', sa.BigInteger(), nullable=False),
                    sa.Column('day_profit_amount', sa.BigInteger(), nullable=False),
                    sa.Column('day_tx_count', sa.BigInteger(), nullable=False),
                    sa.Column('day_refund_count', sa.BigInteger(), nullable=False),
                    sa.Column('clear_report_id', sa.String(length=32), nullable=True),
                    sa.Column('channel', sa.String(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('cs_daily_balance_no')
                    )
    op.create_index(op.f('ix_cs_daily_balance_info_cs_daily_balance_no'),
                    'cs_daily_balance_info', ['cs_daily_balance_no'], unique=False)
    op.create_index(op.f('ix_cs_daily_balance_info_cs_trand_id'),
                    'cs_daily_balance_info', ['cs_trand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cs_daily_balance_info_cs_trand_id'), table_name='cs_daily_balance_info')
    op.drop_index(op.f('ix_cs_daily_balance_info_cs_daily_balance_no'), table_name='cs_daily_balance_info')
    op.drop_table('cs_daily_balance_info')
    # ### end Alembic commands ###
