#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""do_withdraw_loan_id

Revision ID: 84e003fd7f44
Revises: 38720cafbda5
Create Date: 2017-05-11 18:03:19.289188

"""

# 借款id,还款id,附加还款id

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e003fd7f44'
down_revision = '38720cafbda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(u'd0_withdraw', sa.Column('addition_repayment_id', sa.BigInteger(), nullable=True))
    op.add_column(u'd0_withdraw', sa.Column('loan_id', sa.BigInteger(), nullable=True))
    op.add_column(u'd0_withdraw', sa.Column('repayment_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'd0_withdraw', ['loan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'd0_withdraw', type_='unique')
    op.drop_column(u'd0_withdraw', 'repayment_id')
    op.drop_column(u'd0_withdraw', 'loan_id')
    op.drop_column(u'd0_withdraw', 'addition_repayment_id')

    # ### end Alembic commands ###
