"""dt_user table add ali_level column

Revision ID: 86ec62433d08
Revises: 5dbf6e49ee9e
Create Date: 2017-06-21 10:31:37.818505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86ec62433d08'
down_revision = '5dbf6e49ee9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_user', sa.Column('ali_level', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_user', 'ali_level')
    # ### end Alembic commands ###
