"""platform_mch table add column description

Revision ID: 87850318a305
Revises: 501ae56f8814
Create Date: 2017-08-21 14:35:04.809375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87850318a305'
down_revision = '501ae56f8814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_mch', sa.Column('description', sa.String(
        length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_mch', 'description')
    # ### end Alembic commands ###
