#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""wechat channel id

Revision ID: 914dd041b12e
Revises: 154abf307825
Create Date: 2017-04-25 10:14:10.842223

"""
# 渠道商进件到微信、商户进件到微信逻辑修改,增加渠道商进件信息微信渠道号字段
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914dd041b12e'
down_revision = '79cecbbb4f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('use_bank_channel_id',
                                             sa.SmallInteger(), server_default=sa.text(u'1'), nullable=False))
    op.add_column('dt_inlet_info', sa.Column(
        'wx_channel_id', sa.String(length=32), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_inlet_info', 'wx_channel_id')
    op.drop_column('dt_inlet_info', 'use_bank_channel_id')
