"""discount info

Revision ID: a289c147dc64
Revises: e834e43234d6
Create Date: 2017-09-13 15:57:07.639900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a289c147dc64'
down_revision = 'e834e43234d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role', sa.String(length=20), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('discount_type', sa.Integer(), server_default=sa.text(u'1'), nullable=False),
                    sa.Column('rate', sa.String(length=500), nullable=False),
                    sa.Column('valid', sa.Integer(), server_default=sa.text(u'1'), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.Column('update_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    # ### end Alembic commands ###
