#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""auth item nullable columne

Revision ID: a2fae5769b8b
Revises: 71093145ada3
Create Date: 2017-12-06 11:03:56.726589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2fae5769b8b'
down_revision = '71093145ada3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inlet_auth_items', 'sys_name', existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column('inlet_auth_items', 'sys_shortname', existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inlet_auth_items', 'sys_shortname', existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column('inlet_auth_items', 'sys_name', existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###
