"""Add chain related fields

Revision ID: a32840e24f95
Revises: 86ec62433d08
Create Date: 2017-06-23 11:40:49.890791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a32840e24f95'
down_revision = '86ec62433d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mch_user_mch_subuser',
                    sa.Column('mch_id', sa.BigInteger(), nullable=False),
                    sa.Column('mch_sub_id', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('mch_id')
                    )
    op.create_index('mch_user_mch_sub_id_index',
                    'mch_user_mch_subuser', ['mch_sub_id'], unique=True)

    op.add_column('dt_inlet_info', sa.Column('chain_wechat_news',
                                             sa.Integer(), server_default=sa.text(u'1'), nullable=True))

    op.create_index('mch_subuser_index', 'mch_subuser',
                    ['mch_sub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mch_subuser_index', table_name='mch_subuser')
    op.create_foreign_key(u'dt_subuser_dt_user_dt_id_fkey',
                          'dt_subuser', 'dt_user', ['dt_user_dt_id'], ['dt_id'])
    op.drop_column('dt_inlet_info', 'chain_wechat_news')
    op.drop_index('mch_user_mch_sub_id_index',
                  table_name='mch_user_mch_subuser')
    op.drop_table('mch_user_mch_subuser')
    # ### end Alembic commands ###
