"""pre_refund_clear_info pre_d0_clear_info add complete_at

Revision ID: a706153d99e7
Revises: 6d6a80db5948
Create Date: 2017-09-06 17:39:15.221171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a706153d99e7'
down_revision = '6d6a80db5948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_d0_clear_info', sa.Column('complete_at', sa.DateTime(),
                                                 server_default=sa.text(u'now()'), nullable=False))
    op.add_column('pre_refund_clear_info', sa.Column('complete_at', sa.DateTime(),
                                                     server_default=sa.text(u'now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_refund_clear_info', 'complete_at')
    op.drop_column('pre_d0_clear_info', 'complete_at')
    # ### end Alembic commands ###
