"""merchant risk item info

Revision ID: a937823f334c
Revises: f778e84acab3
Create Date: 2017-09-21 19:42:26.696625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a937823f334c'
down_revision = 'f778e84acab3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_risk_item', sa.Column('has_risk', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_risk_item', 'has_risk')
    # ### end Alembic commands ###
