#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""alipay pid

Revision ID: a96d0d88e1fd
Revises: c07840af7d9e
Create Date: 2017-11-10 15:48:00.693732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a96d0d88e1fd'
down_revision = 'c07840af7d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('alipay_pid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dt_inlet_info', 'alipay_pid')
    # ### end Alembic commands ###
