#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""pay_config_info

Revision ID: b07b96c7dc73
Revises: 67d02e8fdccf
Create Date: 2017-07-03 14:10:22.583730

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b07b96c7dc73'
down_revision = '67d02e8fdccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_config_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=True),
                    sa.Column('role_type', sa.String(length=20), nullable=False),
                    sa.Column('config_name', sa.String(length=30), nullable=False),
                    sa.Column('config_value', sa.String(length=200), nullable=False),
                    sa.Column('channel', sa.Integer(), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=False),
                    sa.Column('update_time', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_config_info')
    # ### end Alembic commands ###
