"""pre_trade_clear_info pre_refund_clear_info pre_d0_clear_info add index

Revision ID: b43fe0bbc626
Revises: a706153d99e7
Create Date: 2017-09-12 11:07:42.517017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b43fe0bbc626'
down_revision = 'a706153d99e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pre_trade_clear_info_out_trade_no_index',
                    'pre_trade_clear_info', ['out_trade_no'], unique=True)
    op.create_index('pre_d0_clear_info_out_trade_no_index',
                    'pre_d0_clear_info', ['out_trade_no'], unique=True)
    op.create_index('pre_refund_clear_info_out_refund_no_index',
                    'pre_refund_clear_info', ['out_refund_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pre_trade_clear_info_out_trade_no_index', table_name='pre_trade_clear_info')
    op.drop_index('pre_d0_clear_info_out_trade_no_index', table_name='pre_d0_clear_info')
    op.drop_index('pre_refund_clear_info_out_refund_no_index', table_name='pre_refund_clear_info')
    # ### end Alembic commands ###
