"""add index for mch_user_mch_subuser

Revision ID: bbeb0ff78b56
Revises: 12b1ede583ee
Create Date: 2017-07-31 10:04:15.608428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbeb0ff78b56'
down_revision = '12b1ede583ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('mch_mchuser_subuser_index', 'mch_user_mch_subuser', ['mch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mch_mchuser_subuser_index', table_name='mch_user_mch_subuser')
    # ### end Alembic commands ###
