"""daily cut status

Revision ID: bdfb2e98a635
Revises: 6bba77a8cad7
Create Date: 2017-08-31 17:48:33.001769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdfb2e98a635'
down_revision = '6bba77a8cad7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_payment', sa.Column('daily_cut_status', sa.Integer(), nullable=True))
    op.add_column('mch_payment', sa.Column('daily_cut_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_payment', 'daily_cut_status')
    op.drop_column('dt_payment', 'daily_cut_status')
    # ### end Alembic commands ###
