#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""add jd Industry

Revision ID: c07840af7d9e
Revises: 246a728e54d3
Create Date: 2017-11-01 18:01:19.919856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c07840af7d9e'
down_revision = 'c05009d6e96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_jd_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('industry_code', sa.String(length=40), nullable=False),
                    sa.Column('industry_name', sa.String(length=200), nullable=False),
                    sa.Column('status', sa.Integer(), server_default=sa.text(u'1'), nullable=False),
                    sa.Column('create_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('industry_jd_info_index', 'industry_jd_info', ['industry_code'], unique=True)
    op.add_column('industry_uline_info', sa.Column('jd_ind_code', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_uline_info', 'jd_ind_code')
    op.drop_index('industry_jd_info_index', table_name='industry_jd_info')
    op.drop_table('industry_jd_info')
    # ### end Alembic commands ###
