"""mch_book add column bp_profit dt_profit

Revision ID: c763e561ad8d
Revises: b43fe0bbc626
Create Date: 2017-09-12 11:19:56.085875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c763e561ad8d'
down_revision = 'b43fe0bbc626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_book', sa.Column('bp_profit', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('mch_book', sa.Column('dt_profit', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_book', 'dt_profit')
    op.drop_column('mch_book', 'bp_profit')
    # ### end Alembic commands ###
