#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""chain_notify_url

Revision ID: ca91215f8717
Revises: 7a834f79f256
Create Date: 2017-06-14 18:16:41.268462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca91215f8717'
down_revision = '7a834f79f256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dt_inlet_info', sa.Column('notify_url', sa.String(length=200), nullable=True))
    op.add_column(u'dt_inlet_info', sa.Column('pay_notify_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dt_inlet_info', 'pay_notify_url')
    op.drop_column(u'dt_inlet_info', 'notify_url')
    # ### end Alembic commands ###
