"""modify d0_withdraw column type

Revision ID: cce26eb41ab9
Revises: e755421a8eaa
Create Date: 2017-05-19 12:27:52.425806

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cce26eb41ab9'
down_revision = 'e755421a8eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'd0_withdraw_loan_id_key', 'd0_withdraw', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'd0_withdraw_loan_id_key', 'd0_withdraw', ['loan_id'])
    # ### end Alembic commands ###
