#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""license type

Revision ID: cdf090684bd6
Revises: 02120ca5b195
Create Date: 2017-11-28 15:40:08.379516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdf090684bd6'
down_revision = '02120ca5b195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('license_type', sa.String(length=32), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('license_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_inlet_info', 'license_type')
    op.drop_column('dt_inlet_info', 'license_type')
    # ### end Alembic commands ###
