"""add dt_wx_pay columns

Revision ID: cf74689258c2
Revises: 2c5e04c7efd3
Create Date: 2017-01-10 14:56:34.497905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from uline.public.db import initdb
# from model.uline.balance import MchDailyBalanceInfo, DtDailyBalanceInfo, PDailyBalanceInfo

initdb()
Session = sessionmaker()


# revision identifiers, used by Alembic.
revision = 'cf74689258c2'
down_revision = '2c5e04c7efd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dt_user', sa.Column('wx_sub_mch_id', sa.String(64), nullable=True)
    )
    op.add_column(
        'dt_user', sa.Column('mch_pay_key', sa.String(64), nullable=True)
    )
    op.add_column(
        'mch_user', sa.Column('wx_use_parent', sa.SmallInteger, default=1)
    )

    op.create_table(
        'dt_inlet_to_wx_info',
        sa.Column(
            'id',
            sa.Integer,
            autoincrement=True,
            primary_key=True
        ),
        sa.Column('dt_id', sa.BigInteger, nullable=False),
        sa.Column('return_msg', sa.String(64)),
        sa.Column('return_code', sa.String(64)),
        sa.Column('result_msg', sa.String(64)),
        sa.Column('result_code', sa.String(64)),
        sa.Column('create_at', sa.DateTime),
    )

    # bind = op.get_bind()
    # session = Session(bind=bind)
    #
    # for i in session.query(MchDailyBalanceInfo):
    #     i.mch_trand_id = i.mch_daily_balance_no
    # for i in session.query(DtDailyBalanceInfo):
    #     i.dt_trand_id = i.dt_daily_balance_no
    # for i in session.query(PDailyBalanceInfo):
    #     i.p_trand_id = i.p_daily_balance_no
    # session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'dt_user', sa.Column('wx_sub_mch_id', sa.String(64), nullable=True)
    )
    op.drop_column(
        'dt_user', sa.Column('mch_pay_key', sa.String(64), nullable=True)
    )
    op.drop_column(
        'mch_inlet_info', sa.Column('wx_use_parent', sa.SmallInteger, default=1)
    )

    op.drop_table('dt_inlet_to_wx_info')
    # ### end Alembic commands ###
