#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""head type

Revision ID: d5c386cd68cf
Revises: 602a2a281c9b
Create Date: 2017-12-13 11:31:04.384929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5c386cd68cf'
down_revision = '602a2a281c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_inlet_info', sa.Column('head_type', sa.String(length=64), nullable=True))
    op.add_column('mch_inlet_info', sa.Column('head_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_inlet_info', 'head_type')
    op.drop_column('dt_inlet_info', 'head_type')
    # ### end Alembic commands ###
