#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""chain_dt_sub_id_column

Revision ID: d61ccca3a324
Revises: 4e41438631c4
Create Date: 2017-06-06 11:41:45.177864

"""
# 连锁商户加上业务员
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61ccca3a324'
down_revision = '4e41438631c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dt_inlet_info', sa.Column('dt_sub_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dt_inlet_info', 'dt_sub_id')
    # ### end Alembic commands ###
