"""mch_paymnet dt_payment table add column uline_payment_code

Revision ID: d62ac1b61a84
Revises: f90bafa51e8f
Create Date: 2017-08-28 12:16:07.675535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62ac1b61a84'
down_revision = 'f90bafa51e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_payment', sa.Column('uline_payment_code', sa.String(length=64), nullable=True))
    op.add_column('mch_payment', sa.Column('uline_payment_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_payment', 'uline_payment_code')
    op.drop_column('dt_payment', 'uline_payment_code')
    # ### end Alembic commands ###
