"""modifycommentlength

Revision ID: de2db21d571b
Revises: 9ddeca72e332
Create Date: 2017-05-26 14:45:20.722330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2db21d571b'
down_revision = '9ddeca72e332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'auth_dt_info', 'comment',
                    existing_type=sa.String(64),
                    type_=sa.String(1024),
                    existing_nullable=False)
    op.alter_column(u'auth_mch_info', 'comment',
                    existing_type=sa.String(64),
                    type_=sa.String(1024),
                    existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
