"""add alipay_sub_mch_id and create bank_no index

Revision ID: df25824f0ffc
Revises: 98b49652632b
Create Date: 2016-12-08 10:08:53.027509

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'df25824f0ffc'
down_revision = '98b49652632b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_user', sa.Column('alipay_sub_mch_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_balance_bank_info_bank_name'), 'balance_bank_info', ['bank_name'], unique=False,
                    )
    op.create_index(op.f('ix_balance_bank_info_bank_no'), 'balance_bank_info', ['bank_no'], unique=True,
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_user', 'alipay_sub_mch_id')
    op.drop_index(op.f('ix_balance_bank_info_bank_no'), table_name='balance_bank_info')
    op.drop_index(op.f('ix_balance_bank_info_bank_name'), table_name='balance_bank_info')
    ### end Alembic commands ###
