#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""d0_withdraw add column fee_date

Revision ID: e03f2ea0666d
Revises: 035fa6373ba0
Create Date: 2017-10-27 15:43:10.806612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e03f2ea0666d'
down_revision = '035fa6373ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('d0_withdraw', sa.Column('fee_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('d0_withdraw', 'fee_date')
    # ### end Alembic commands ###
