"""modify dt_clear_info current_balance

Revision ID: e755421a8eaa
Revises: 72122a41d691
Create Date: 2017-05-18 19:07:56.103288

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e755421a8eaa'
down_revision = '72122a41d691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'dt_clear_info', 'current_balance',
                    existing_type=sa.SMALLINT(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'dt_clear_info', 'current_balance',
                    existing_type=sa.BigInteger(),
                    type_=sa.SMALLINT(),
                    existing_nullable=True)
    # ### end Alembic commands ###
