"""risk control table

Revision ID: e7b0539124fd
Revises: 6bd32a87b858
Create Date: 2017-09-27 11:19:38.358157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7b0539124fd'
down_revision = '6bd32a87b858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_control',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sys_id', sa.BigInteger(), nullable=True),
                    sa.Column('sys_type_id', sa.String(length=64), nullable=True),
                    sa.Column('credit', sa.String(length=200), nullable=True),
                    sa.Column('pay', sa.String(length=200), nullable=True),
                    sa.Column('settle', sa.String(length=200), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.Column('update_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_control')
    # ### end Alembic commands ###
