#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mch discount record

Revision ID: e8903a5ed0e4
Revises: e7b0539124fd
Create Date: 2017-10-04 16:10:48.687177

"""

from alembic import op
import sqlalchemy as sa
# 用于记录银行发放的优惠

# revision identifiers, used by Alembic.
revision = 'e8903a5ed0e4'
down_revision = 'e7b0539124fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('discount_record',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('discount_id', sa.BigInteger(), nullable=False),
                    sa.Column('daily_balance_id', sa.BigInteger(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('amount', sa.BigInteger(), nullable=False),
                    sa.Column('rate', sa.BigInteger(), nullable=False),
                    sa.Column('channel', sa.String(length=64), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('daily_balance_id')
                    )

    op.add_column(u'mch_daily_balance_info', sa.Column('discount_amount', sa.BigInteger(), nullable=True))

    op.add_column(u'p_daily_balance_info', sa.Column('discount_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'p_daily_balance_info', 'discount_amount')
    op.drop_column(u'mch_daily_balance_info', 'discount_amount')

    op.drop_index('discount_record_id_seq', table_name='discount_record')
    op.drop_table('discount_record')
    # ### end Alembic commands ###
