"""message_send_info

Revision ID: eff79cb040e9
Revises: 7cbf2dc530fb
Create Date: 2017-07-17 12:38:04.198644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff79cb040e9'
down_revision = 'f7bd7231435f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_content_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message_content', sa.String(
                        length=200), nullable=False),
                    sa.Column('create_at', sa.DateTime(),
                              server_default=sa.text(u'now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('message_send_info',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('send_id', sa.Integer(), nullable=False),
                    sa.Column('mch_id', sa.BigInteger(), nullable=False),
                    sa.Column('dt_id', sa.BigInteger(), nullable=False),
                    sa.Column('send_status', sa.SmallInteger(), nullable=True),
                    sa.Column('create_at', sa.DateTime(),
                              server_default=sa.text(u'now()'), nullable=False),
                    sa.Column('send_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_send_info')
    op.drop_table('message_content_info')
    # ### end Alembic commands ###
