#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mch_user add jd_sub_mch_id

Revision ID: f3e917ae04ed
Revises: e03f2ea0666d
Create Date: 2017-11-02 17:46:53.480885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3e917ae04ed'
down_revision = 'e03f2ea0666d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_user', sa.Column('jd_sub_mch_id', sa.String(length=32), nullable=True))
    op.add_column('mch_user', sa.Column('jd_sub_mch_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_user', 'jd_sub_mch_id')
    op.drop_column('dt_user', 'jd_sub_mch_id')
    # ### end Alembic commands ###
