# -*- coding:utf-8 -*-

"""mch_balance add valid

Revision ID: f7bd7231435f
Revises: 7cbf2dc530fb
Create Date: 2017-07-26 16:50:44.999719

"""
from alembic import op
import sqlalchemy as sa

# 冻结账户使用  默认为空 冻结为1 解冻为2

# revision identifiers, used by Alembic.
revision = 'f7bd7231435f'
down_revision = '7cbf2dc530fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_balance', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_balance', 'status')
    # ### end Alembic commands ###
