"""mch_paymnet dt_payment table add column withdraw_fee

Revision ID: f90bafa51e8f
Revises: 07bd153f9dbb
Create Date: 2017-08-25 10:34:47.924117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f90bafa51e8f'
down_revision = '07bd153f9dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dt_payment', sa.Column('withdraw_fee', sa.Integer(), nullable=True))
    op.add_column('mch_payment', sa.Column('withdraw_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_payment', 'withdraw_fee')
    op.drop_column('dt_payment', 'withdraw_fee')
    # ### end Alembic commands ###
