#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""chain_ali_sub_id

Revision ID: faadc55299de
Revises: 3d86de5a471d
Create Date: 2017-06-15 15:10:02.208472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faadc55299de'
down_revision = '3d86de5a471d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dt_user', sa.Column('ali_sub_mch_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dt_user', 'ali_sub_mch_id')
    # ### end Alembic commands ###
