"""mch_user add column refund_password

Revision ID: fd36934be52d
Revises: 301ce165cc36
Create Date: 2017-03-22 12:33:51.318921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd36934be52d'
down_revision = '301ce165cc36'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mch_user', sa.Column('refund_password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mch_user', 'refund_password')
    # ### end Alembic commands ###
